/** Shell completion scripts for expert terminals. */
export function shellCompletionScript(shell: string): string {
  const cmds =
    "run login logout auth sessions init models doctor stats tips news status completion prune-tool-output prune-metrics";
  const zshCmds = cmds.split(" ").join(" ");
  const runFlags =
    "--json --ulw --permission-mode --model --provider --base-url --goal --session --continue --new --title --sandbox --sandbox-network --sandbox-missing --deny --allow --ask --cwd --effort";
  const topFlags =
    "--new --session --title --model --provider --permission-mode --ulw --goal --cwd --sandbox --help --version";
  const sessionsActions =
    "list show path export import fork pin unpin delete prune";
  const sessionsFlags =
    "--json --out --format --keep --max-age-days --cwd --query -q --pinned --limit -n --force";
  // --cwd: list filter + import override; --query/-q: list id/title filter; --pinned

  if (shell === "zsh") {
    return [
      "#compdef forge",
      '# Install: forge completion zsh > "${fpath[1]}/_forge" && compinit',
      "_forge() {",
      "  local context state state_descr line",
      "  typeset -A opt_args",
      "  local -a cmds",
      `  cmds=(${zshCmds})`,
      "  _arguments -C \\",
      "    '1:command:->cmds' \\",
      "    '*::arg:->args'",
      "  case $state in",
      "    cmds)",
      "      _describe 'command' cmds",
      "      _values 'flags' ${topFlags}",
      "      ;;",
      "    args)",
      "      case $line[1] in",
      "        run)",
      `          _values 'run flags' ${runFlags}`,
      "          ;;",
      "        sessions)",
      "          if (( CURRENT == 2 )); then",
      `            _values 'sessions' ${sessionsActions}`,
      "          else",
      "            case $line[2] in",
      "              export)",
      "                _values 'export' --format --out --json md json markdown",
      "                ;;",
      "              import)",
      "                _files",
      "                _values 'import' --cwd --json",
      "                ;;",
      "              prune)",
      "                _values 'prune' --keep --max-age-days --json",
      "                ;;",
      "              delete)",
      "                _values 'delete' --json --force",
      "                ;;",
      "              list)",
      "                _values 'list' --json --limit -n --cwd --query -q --pinned",
      "                ;;",
      "              show|path|fork|pin|unpin)",
      "                _values 'flags' --json",
      "                ;;",
      "              *)",
      `                _values 'sessions flags' ${sessionsFlags}`,
      "                ;;",
      "            esac",
      "          fi",
      "          ;;",
      "        doctor|models|status|auth)",
      "          _values 'flags' --json",
      "          ;;",
      "        stats)",
      "          _values 'stats' --json --days",
      "          ;;",
      "        news|changelog)",
      "          _values 'news' --json 1 2 3",
      "          ;;",
      "        login)",
      "          _values 'login' --api-key --oauth --device --from-grok --provider",
      "          ;;",
      "        completion)",
      "          _values 'shell' bash zsh fish",
      "          ;;",
      "        prune-tool-output|prune-metrics)",
      "          _values 'flags' --json --keep",
      "          ;;",
      "      esac",
      "      ;;",
      "  esac",
      "}",
      "compdef _forge forge",
      "",
    ].join("\n");
  }

  if (shell === "fish") {
    return [
      "# Install: forge completion fish > ~/.config/fish/completions/forge.fish",
      "complete -c forge -f",
      `complete -c forge -n "__fish_use_subcommand" -a "${cmds}"`,
      'complete -c forge -l help -d "Help"',
      'complete -c forge -l version -d "Version"',
      'complete -c forge -l model -d "Model id"',
      'complete -c forge -l provider -d "Provider"',
      'complete -c forge -l permission-mode -d "Permission mode"',
      'complete -c forge -l sandbox -d "OS sandbox profile"',
      'complete -c forge -l ulw -d "Ultrawork"',
      'complete -c forge -l goal -d "Arm /goal"',
      'complete -c forge -l json -d "JSON output"',
      'complete -c forge -l new -d "Force a new session (skip same-cwd auto-resume)"',
      'complete -c forge -l session -d "Resume session id/prefix"',
      'complete -c forge -l title -d "Label for a new session"',
      'complete -c forge -l cwd -d "Workspace directory"',
      // run subcommand
      'complete -c forge -n "__fish_seen_subcommand_from run" -l json -d "JSON result"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l ulw -d "Ultrawork"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l permission-mode -d "Permission mode"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox -d "OS sandbox"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox-network -d "Bash network"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox-missing -d "Missing backend policy"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l model -d "Model id"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l base-url -d "API base URL"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l goal -d "Arm /goal"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l session -d "Resume session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l continue -d "Resume newest same-cwd session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l new -d "New session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l title -d "Label for a new session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l deny -d "Deny rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l allow -d "Allow rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l ask -d "Ask rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l cwd -d "Workspace"',
      'complete -c forge -n "__fish_seen_subcommand_from doctor" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from models" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from status" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from auth" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from stats" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from stats" -l days -d "Last N days"',
      'complete -c forge -n "__fish_seen_subcommand_from news" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from news" -a "1 2 3" -d "Release count"',
      `complete -c forge -n "__fish_seen_subcommand_from sessions; and not __fish_seen_subcommand_from ${sessionsActions}" -a "${sessionsActions}"`,
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l out -d "Export output path"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l format -d "Export format md|json" -a "md json markdown"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l keep -d "Prune keep newest N"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l max-age-days -d "Prune max age days"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l cwd -d "List filter or import cwd override"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l query -s q -d "List id/title substring filter"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l pinned -d "List only pin-protected sessions"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l limit -d "List limit"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l force -d "Delete even if session is locked"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l api-key -d "API key"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l oauth -d "Browser OAuth"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l device -d "Device code"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l from-grok -d "Import Grok creds"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-tool-output" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-tool-output" -l keep -d "Keep newest N"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-metrics" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-metrics" -l keep -d "Keep newest N"',
      "",
    ].join("\n");
  }

  // bash — context-aware sessions subcommands + flags
  return [
    '# Install: eval "$(forge completion bash)"',
    "# or: forge completion bash > /usr/local/etc/bash_completion.d/forge",
    "_forge_completions() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    '  local prev_word="${COMP_WORDS[COMP_CWORD-1]}"',
    `  local cmds="${cmds}"`,
    `  local top_flags="${topFlags}"`,
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    '    COMPREPLY=( $(compgen -W "$cmds $top_flags" -- "$cur") )',
    "    return",
    "  fi",
    '  local cmd="${COMP_WORDS[1]}"',
    '  case "$cmd" in',
    "    sessions)",
    "      if [[ ${COMP_CWORD} -eq 2 ]]; then",
    `        COMPREPLY=( $(compgen -W "${sessionsActions}" -- "$cur") )`,
    "        return",
    "      fi",
    '      local act="${COMP_WORDS[2]}"',
    '      if [[ "$prev_word" == "--format" ]]; then',
    '        COMPREPLY=( $(compgen -W "md json markdown" -- "$cur") )',
    "        return",
    "      fi",
    '      case "$act" in',
    `        export) COMPREPLY=( $(compgen -W "--format --out --json" -- "$cur") ) ;;`,
    `        import) COMPREPLY=( $(compgen -W "--cwd --json" -- "$cur") ) ;;`,
    `        prune) COMPREPLY=( $(compgen -W "--keep --max-age-days --json" -- "$cur") ) ;;`,
    `        delete) COMPREPLY=( $(compgen -W "--json --force" -- "$cur") ) ;;`,
    `        show|path|fork|pin|unpin) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;`,
    `        list) COMPREPLY=( $(compgen -W "--json --limit -n --cwd --query -q --pinned" -- "$cur") ) ;;`,
    `        *) COMPREPLY=( $(compgen -W "${sessionsFlags}" -- "$cur") ) ;;`,
    "      esac",
    "      ;;",
    '    doctor|models|status|auth) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;',
    '    stats) COMPREPLY=( $(compgen -W "--json --days" -- "$cur") ) ;;',
    '    news|changelog) COMPREPLY=( $(compgen -W "--json 1 2 3" -- "$cur") ) ;;',
    `    run) COMPREPLY=( $(compgen -W "${runFlags}" -- "$cur") ) ;;`,
    '    login) COMPREPLY=( $(compgen -W "--api-key --oauth --device --from-grok --provider" -- "$cur") ) ;;',
    '    completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;',
    '    prune-tool-output|prune-metrics) COMPREPLY=( $(compgen -W "--json --keep" -- "$cur") ) ;;',
    '    --new|--session|--model|--provider|--permission-mode|--ulw|--goal|--cwd|--sandbox|--help|--version)',
    '      COMPREPLY=( $(compgen -W "$top_flags" -- "$cur") ) ;;',
    "  esac",
    "}",
    "complete -F _forge_completions forge",
    "",
  ].join("\n");
}
