/** Shell completion scripts for expert terminals. */
export const COMPLETION_SHELLS = ["bash", "zsh", "fish"] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

/** Normalize / validate shell name. Empty → bash. Unknown → null. */
export function normalizeCompletionShell(
  shell: string | undefined | null,
): CompletionShell | null {
  const s = String(shell ?? "bash").trim().toLowerCase() || "bash";
  if ((COMPLETION_SHELLS as readonly string[]).includes(s)) {
    return s as CompletionShell;
  }
  return null;
}

export function shellCompletionScript(shell: string): string {
  const cmds =
    "run login logout auth accounts sessions init models doctor stats tips news logs config status completion prune-tool-output prune-metrics";
  const zshCmds = cmds.split(" ").join(" ");
  const runFlags =
    "--json --ulw --permission-mode --model --provider --base-url --goal --session --continue --new --title --sandbox --sandbox-network --sandbox-missing --read-outside --deny --allow --ask --cwd --effort --max-turns --no-blocking-stop";
  const topFlags =
    "--new --session --continue --title --json --model --provider --base-url --permission-mode --ulw --goal --cwd --sandbox --sandbox-network --sandbox-missing --read-outside --deny --allow --ask --effort --max-turns --no-blocking-stop --help --version";
  const sessionsActions =
    "list show path export import fork pin unpin title rename delete prune search find";
  const sessionsFlags =
    "--json --out --format --keep --max-age-days --cwd --query -q --pinned --limit -n --force";
  // --cwd: list filter + import override; --query/-q: list id/title filter; --pinned

  const normalized = normalizeCompletionShell(shell);
  if (!normalized) {
    throw new Error(
      `Unknown completion shell "${shell}". Use bash, zsh, or fish.`,
    );
  }
  if (normalized === "zsh") {
    return [
      "#compdef forge",
      '# Install: forge completion zsh > "${fpath[1]}/_forge" && compinit',
      "_forge() {",
      "  local context state state_descr line",
      "  typeset -A opt_args",
      "  local -a cmds",
      `  cmds=(${zshCmds})`,
      "  _arguments -C \\",
      "    '1:command:->cmds' \\",
      "    '*::arg:->args'",
      "  case $state in",
      "    cmds)",
      "      _describe 'command' cmds",
      "      _values 'flags' ${topFlags}",
      "      ;;",
      "    args)",
      "      case $words[CURRENT-1] in",
      "        --permission-mode)",
      "          _values 'permission-mode' default acceptEdits plan bypassPermissions dontAsk accept deny ask yolo",
      "          return",
      "          ;;",
      "        --effort|--reasoning-effort)",
      "          _values 'effort' low medium high lo med hi max",
      "          return",
      "          ;;",
      "        --sandbox)",
      "          _values 'sandbox' off workspace read-only strict readonly ro ws none full",
      "          return",
      "          ;;",
      "        --sandbox-network)",
      "          _values 'sandbox-network' unrestricted blocked",
      "          return",
      "          ;;",
      "        --sandbox-missing)",
      "          _values 'sandbox-missing' fail-closed fallback",
      "          return",
      "          ;;",
      "        --read-outside)",
      "          _values 'read-outside' ask allow deny",
      "          return",
      "          ;;",
      "        -p|--provider)",
      "          _values 'provider' xai anthropic openai openrouter google copilot custom grok claude sonnet opus haiku gpt oai chatgpt gemini bard or router github github-copilot gh-copilot",
      "          return",
      "          ;;",
      "      esac",
      "      case $line[1] in",
      "        run)",
      `          _values 'run flags' ${runFlags}`,
      "          ;;",
      "        sessions)",
      "          if (( CURRENT == 2 )); then",
      `            _values 'sessions' ${sessionsActions}`,
      "          else",
      "            case $line[2] in",
      "              export)",
      "                _values 'export' --format --out --json md json markdown",
      "                ;;",
      "              import)",
      "                _files",
      "                _values 'import' --cwd --json",
      "                ;;",
      "              prune)",
      "                _values 'prune' --keep --max-age-days --json",
      "                ;;",
      "              delete)",
      "                _values 'delete' --json --force",
      "                ;;",
      "              list)",
      "                _values 'list' --json --limit -n --cwd --query -q --pinned",
      "                ;;",
      "              show|path|fork|pin|unpin|title|rename)",
      "                _values 'flags' --json",
      "                ;;",
      "              *)",
      `                _values 'sessions flags' ${sessionsFlags}`,
      "                ;;",
      "            esac",
      "          fi",
      "          ;;",
      "        doctor|models)",
      "          _values 'flags' --json --provider -p",
      "          ;;",
      "        status|auth|tips|init|completion)",
      "          _values 'flags' --json",
      "          ;;",
      "        accounts)",
      "          _values 'accounts' list switch remove rename priority disable enable auto-switch --json --provider",
      "          ;;",
      "        stats)",
      "          _values 'stats' --json --days",
      "          ;;",
      "        news|changelog)",
      "          _values 'news' --json 1 2 3",
      "          ;;",
      "        logs)",
      "          _values 'logs' --json --path --lines -n",
      "          ;;",
      "        config)",
      "          _values 'config' --json --provider --model --cwd --max-turns --sandbox --sandbox-missing --sandbox-network --read-outside --permission-mode --no-blocking-stop",
      "          ;;",
      "        login)",
      "          _values 'login' --api-key --oauth --device --from-grok --from-copilot --add --label --provider --json",
      "          ;;",
      "        logout)",
      "          _values 'logout' --provider --json",
      "          ;;",
      "        completion)",
      "          _values 'shell' bash zsh fish",
      "          ;;",
      "        prune-tool-output|prune-metrics)",
      "          _values 'flags' --json --keep",
      "          ;;",
      "      esac",
      "      ;;",
      "  esac",
      "}",
      "compdef _forge forge",
      "",
    ].join("\n");
  }

  if (normalized === "fish") {
    return [
      "# Install: forge completion fish > ~/.config/fish/completions/forge.fish",
      "complete -c forge -f",
      `complete -c forge -n "__fish_use_subcommand" -a "${cmds}"`,
      'complete -c forge -l help -d "Help"',
      'complete -c forge -l version -d "Version"',
      'complete -c forge -l model -d "Model id"',
      'complete -c forge -l provider -d "Provider" -x -a "xai anthropic openai openrouter google copilot custom grok claude sonnet opus haiku gpt oai chatgpt gemini bard or router github github-copilot gh-copilot"',
      'complete -c forge -l permission-mode -d "Permission mode" -x -a "default acceptEdits plan bypassPermissions dontAsk accept deny ask yolo"',
      'complete -c forge -l sandbox -d "OS sandbox profile" -x -a "off workspace read-only strict readonly ro ws none full"',
      'complete -c forge -l sandbox-network -d "Bash network"',
      'complete -c forge -l sandbox-missing -d "Missing backend policy"',
      'complete -c forge -l read-outside -d "Read outside workspace policy"',
      'complete -c forge -l effort -d "Reasoning effort"',
      'complete -c forge -l base-url -d "API base URL"',
      'complete -c forge -l deny -d "Deny rule"',
      'complete -c forge -l allow -d "Allow rule"',
      'complete -c forge -l ask -d "Ask rule"',
      'complete -c forge -l max-turns -d "Cap agent turns"',
      'complete -c forge -l ulw -d "Ultrawork"',
      'complete -c forge -l goal -d "Arm /goal"',
      'complete -c forge -l json -d "JSON output (headless bare forge parity with run --json)"',
      'complete -c forge -l new -d "Force a new session (skip same-cwd auto-resume)"',
      'complete -c forge -l session -d "Resume session id/prefix"',
      'complete -c forge -l continue -d "Resume newest same-cwd session (headless bare forge)"',
      'complete -c forge -l title -d "Label for a new session"',
      'complete -c forge -l cwd -d "Workspace directory"',
      // run subcommand
      'complete -c forge -n "__fish_seen_subcommand_from run" -l json -d "JSON result"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l ulw -d "Ultrawork"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l permission-mode -d "Permission mode" -x -a "default acceptEdits plan bypassPermissions dontAsk accept deny ask yolo"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox -d "OS sandbox" -x -a "off workspace read-only strict readonly ro ws none full"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox-network -d "Bash network"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l sandbox-missing -d "Missing backend policy"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l read-outside -d "Read outside workspace policy"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l model -d "Model id"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l provider -d "Provider" -x -a "xai anthropic openai openrouter google copilot custom grok claude sonnet opus haiku gpt oai chatgpt gemini bard or router github github-copilot gh-copilot"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l base-url -d "API base URL"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l goal -d "Arm /goal"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l session -d "Resume session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l continue -d "Resume newest same-cwd session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l new -d "New session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l title -d "Label for a new session"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l deny -d "Deny rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l allow -d "Allow rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l ask -d "Ask rule"',
      'complete -c forge -n "__fish_seen_subcommand_from run" -l cwd -d "Workspace"',
      'complete -c forge -n "__fish_seen_subcommand_from doctor" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from doctor" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from doctor" -s p -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from models" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from models" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from models" -s p -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from status" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from auth" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from accounts" -a "list switch remove rename priority disable enable auto-switch" -d "Accounts subcommand"',
      'complete -c forge -n "__fish_seen_subcommand_from accounts" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from accounts" -l provider -d "Provider filter"',
      'complete -c forge -n "__fish_seen_subcommand_from tips" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from init" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from completion" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from stats" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from stats" -l days -d "Last N days"',
      'complete -c forge -n "__fish_seen_subcommand_from news" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from news" -a "1 2 3" -d "Release count"',
      'complete -c forge -n "__fish_seen_subcommand_from logs" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from logs" -l path -d "Print log path"',
      'complete -c forge -n "__fish_seen_subcommand_from logs" -l lines -s n -d "Event count"',
      'complete -c forge -n "__fish_seen_subcommand_from config" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from config" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from config" -l model -d "Model"',
      'complete -c forge -n "__fish_seen_subcommand_from config" -l cwd -d "Workspace"',
      `complete -c forge -n "__fish_seen_subcommand_from sessions; and not __fish_seen_subcommand_from ${sessionsActions}" -a "${sessionsActions}"`,
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l out -d "Export output path"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l format -d "Export format md|json" -a "md json markdown"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l keep -d "Prune keep newest N" -x -a "0 all max unlimited 10 50 100"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l max-age-days -d "Prune max age days" -x -a "0 all none off 7 14 30 90"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l cwd -d "List filter or import cwd override"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l query -s q -d "List id/title substring filter"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l pinned -d "List only pin-protected sessions"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l limit -d "List limit (0/all/max)" -x -a "0 all max unlimited 30 50 100"',
      'complete -c forge -n "__fish_seen_subcommand_from sessions" -l force -d "Delete even if session is locked"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l api-key -d "API key"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l oauth -d "Browser OAuth"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l device -d "Device code"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l from-grok -d "Import Grok creds"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l from-copilot -d "Import local Copilot"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l add -d "Add another account"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l label -d "Account label"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from login" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from logout" -l provider -d "Provider"',
      'complete -c forge -n "__fish_seen_subcommand_from logout" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-tool-output" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-tool-output" -l keep -d "Keep newest N" -x -a "0 all max unlimited 10 50 80 100"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-metrics" -l json -d "JSON"',
      'complete -c forge -n "__fish_seen_subcommand_from prune-metrics" -l keep -d "Keep newest N" -x -a "0 all max unlimited 50 100 500"',
      "",
    ].join("\n");
  }

  // bash (default) — context-aware sessions subcommands + flags
  return [
    '# Install: eval "$(forge completion bash)"',
    "# or: forge completion bash > /usr/local/etc/bash_completion.d/forge",
    "_forge_completions() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    '  local prev_word="${COMP_WORDS[COMP_CWORD-1]}"',
    `  local cmds="${cmds}"`,
    `  local top_flags="${topFlags}"`,
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    '    COMPREPLY=( $(compgen -W "$cmds $top_flags" -- "$cur") )',
    "    return",
    "  fi",
    '  # Enum flag values (parent or run)',
    '  case "$prev_word" in',
    '    --permission-mode)',
    '      COMPREPLY=( $(compgen -W "default acceptEdits plan bypassPermissions dontAsk accept deny ask yolo" -- "$cur") )',
    "      return",
    "      ;;",
    '    --effort|--reasoning-effort)',
    '      COMPREPLY=( $(compgen -W "low medium high lo med hi max" -- "$cur") )',
    "      return",
    "      ;;",
    '    --sandbox)',
    '      COMPREPLY=( $(compgen -W "off workspace read-only strict readonly ro ws none full" -- "$cur") )',
    "      return",
    "      ;;",
    '    --sandbox-network)',
    '      COMPREPLY=( $(compgen -W "unrestricted blocked" -- "$cur") )',
    "      return",
    "      ;;",
    '    --sandbox-missing)',
    '      COMPREPLY=( $(compgen -W "fail-closed fallback" -- "$cur") )',
    "      return",
    "      ;;",
    "    --read-outside)",
    '      COMPREPLY=( $(compgen -W "ask allow deny" -- "$cur") )',
    "      return",
    "      ;;",
    "    -p|--provider)",
    '      COMPREPLY=( $(compgen -W "xai anthropic openai openrouter google copilot custom grok claude sonnet opus haiku gpt oai chatgpt gemini bard or router github github-copilot gh-copilot" -- "$cur") )',
    "      return",
    "      ;;",
    '    --keep)',
    '      COMPREPLY=( $(compgen -W "0 all max unlimited 10 50 80 100 500" -- "$cur") )',
    "      return",
    "      ;;",
    '    --max-age-days)',
    '      COMPREPLY=( $(compgen -W "0 all none off 7 14 30 90" -- "$cur") )',
    "      return",
    "      ;;",
    "  esac",
    '  local cmd="${COMP_WORDS[1]}"',
    '  case "$cmd" in',
    "    sessions)",
    "      if [[ ${COMP_CWORD} -eq 2 ]]; then",
    `        COMPREPLY=( $(compgen -W "${sessionsActions}" -- "$cur") )`,
    "        return",
    "      fi",
    '      local act="${COMP_WORDS[2]}"',
    '      if [[ "$prev_word" == "--format" ]]; then',
    '        COMPREPLY=( $(compgen -W "md json markdown" -- "$cur") )',
    "        return",
    "      fi",
    '      if [[ "$prev_word" == "--limit" || "$prev_word" == "-n" ]]; then',
    '        COMPREPLY=( $(compgen -W "0 all max unlimited 30 50 100" -- "$cur") )',
    "        return",
    "      fi",
    '      if [[ "$prev_word" == "--max-age-days" ]]; then',
    '        COMPREPLY=( $(compgen -W "0 all none off 7 14 30 90" -- "$cur") )',
    "        return",
    "      fi",
    '      if [[ "$prev_word" == "--keep" ]]; then',
    '        COMPREPLY=( $(compgen -W "0 all max unlimited 10 50 80 100 500" -- "$cur") )',
    "        return",
    "      fi",
    '      case "$act" in',
    `        export) COMPREPLY=( $(compgen -W "--format --out --json" -- "$cur") ) ;;`,
    `        import) COMPREPLY=( $(compgen -W "--cwd --json" -- "$cur") ) ;;`,
    `        prune) COMPREPLY=( $(compgen -W "--keep --max-age-days --json" -- "$cur") ) ;;`,
    `        delete) COMPREPLY=( $(compgen -W "--json --force" -- "$cur") ) ;;`,
    `        show|path|fork|pin|unpin|title|rename) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;`,
    `        list) COMPREPLY=( $(compgen -W "--json --limit -n --cwd --query -q --pinned" -- "$cur") ) ;;`,
    `        *) COMPREPLY=( $(compgen -W "${sessionsFlags}" -- "$cur") ) ;;`,
    "      esac",
    "      ;;",
    '    doctor) COMPREPLY=( $(compgen -W "--json --provider -p --cwd --max-turns --sandbox --sandbox-missing --sandbox-network --read-outside --permission-mode --no-blocking-stop" -- "$cur") ) ;;',
    '    models) COMPREPLY=( $(compgen -W "--json --provider -p" -- "$cur") ) ;;',
    '    status|auth|tips|init|completion|accounts) COMPREPLY=( $(compgen -W "list switch remove rename priority disable enable auto-switch --json" -- "$cur") ) ;;',
    '    stats) COMPREPLY=( $(compgen -W "--json --days" -- "$cur") ) ;;',
    '    news|changelog) COMPREPLY=( $(compgen -W "--json 1 2 3" -- "$cur") ) ;;',
    '    logs) COMPREPLY=( $(compgen -W "--json --path --lines -n" -- "$cur") ) ;;',
    '    config) COMPREPLY=( $(compgen -W "--json --provider --model --cwd --max-turns --sandbox --sandbox-missing --sandbox-network --read-outside --permission-mode --no-blocking-stop" -- "$cur") ) ;;',
    `    run) COMPREPLY=( $(compgen -W "${runFlags}" -- "$cur") ) ;;`,
    '    login) COMPREPLY=( $(compgen -W "--api-key --oauth --device --from-grok --from-copilot --add --label --provider --json" -- "$cur") ) ;;',
    '    logout) COMPREPLY=( $(compgen -W "--provider --json" -- "$cur") ) ;;',
    '    completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;',
    '    prune-tool-output|prune-metrics) COMPREPLY=( $(compgen -W "--json --keep" -- "$cur") ) ;;',
    '    --new|--session|--continue|--title|--json|--model|--provider|--permission-mode|--ulw|--goal|--cwd|--sandbox|--help|--version)',
    '      COMPREPLY=( $(compgen -W "$top_flags" -- "$cur") ) ;;',
    "  esac",
    "}",
    "complete -F _forge_completions forge",
    "",
  ].join("\n");
}
